name: "Message PR to slack"
on: push
  # pull_request:
  #   types:
  #     - opened

jobs:
  send-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "PR Created \n Link: <${{ github.event.pull_request.html_url }}|Link> \n branch: `${{ github.ref_name }}`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR Created \n Link: <${{ github.event.pull_request.html_url }}|Link> \n branch: `${{ github.ref_name }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
